# Generated by Django 5.2.17 on 2026-08-18 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PresenceMembre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PRESENT', 'Présent'), ('ABSENT', 'Absent'), ('EXCUSED', 'Excusé')], default='PRESENT', max_length=10, verbose_name='Statut')),
                ('check_in_time', models.DateTimeField(blank=True, null=True, verbose_name="Heure d'arrivée")),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
            ],
            options={
                'verbose_name': 'Présence',
                'verbose_name_plural': 'Présences',
            },
        ),
        migrations.CreateModel(
            name='SessionCulte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service_type', models.CharField(choices=[('SABBATH', 'Sabbat'), ('SUNDAY', 'Dimanche'), ('WEDNESDAY', 'Mercredi'), ('FRIDAY', 'Vendredi'), ('SPECIAL', 'Spécial'), ('OTHER', 'Autre')], default='SABBATH', max_length=20, verbose_name='Type de culte')),
                ('date', models.DateField(verbose_name='Date')),
                ('men_count', models.PositiveIntegerField(default=0, verbose_name='Hommes')),
                ('women_count', models.PositiveIntegerField(default=0, verbose_name='Femmes')),
                ('children_count', models.PositiveIntegerField(default=0, verbose_name='Enfants')),
                ('visitors_count', models.PositiveIntegerField(default=0, verbose_name='Visiteurs')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
            ],
            options={
                'verbose_name': 'Session de culte',
                'verbose_name_plural': 'Sessions de culte',
                'ordering': ['-date'],
            },
        ),
    ]
