# Generated by Django 5.2.17 on 2026-08-18 13:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendance', '0001_initial'),
        ('hierarchy', '0001_initial'),
        ('members', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='presencemembre',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='members.membre', verbose_name='Membre'),
        ),
        migrations.AddField(
            model_name='sessionculte',
            name='church',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='worship_sessions', to='hierarchy.entitehierarchique', verbose_name='Église'),
        ),
        migrations.AddField(
            model_name='sessionculte',
            name='leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Responsable'),
        ),
        migrations.AddField(
            model_name='presencemembre',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='attendance.sessionculte', verbose_name='Session'),
        ),
        migrations.AlterUniqueTogether(
            name='presencemembre',
            unique_together={('session', 'member')},
        ),
    ]
