# Generated by Django 5.2.17 on 2026-08-18 13:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.CharField(choices=[('EMAIL', 'Email'), ('WHATSAPP', 'WhatsApp'), ('IN_APP', "Dans l'application")], max_length=15)),
                ('notification_type', models.CharField(choices=[('RECEIPT', 'Reçu'), ('DONATION_VALIDATED', 'Don validé'), ('DONATION_CANCELLED', 'Don annulé'), ('EVENT_REMINDER', "Rappel d'événement"), ('EVENT_UPDATED', 'Événement modifié'), ('BUDGET_ALERT', 'Alerte budget'), ('TRANSFER_REQUEST', 'Demande de transfert'), ('TRANSFER_APPROVED', 'Transfert approuvé'), ('PASSWORD_RESET', 'Réinitialisation du mot de passe'), ('SECURITY_ALERT', 'Alerte sécurité'), ('WELCOME', 'Bienvenue'), ('OTHER', 'Autre')], max_length=30)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('related_object_type', models.CharField(blank=True, max_length=100, null=True)),
                ('related_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('SENT', 'Envoyé'), ('FAILED', 'Échec'), ('READ', 'Lu')], default='PENDING', max_length=15)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('recipient_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='members.membre')),
                ('recipient_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
