# Generated by Django 5.2.17 on 2026-08-18 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hierarchy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Famille',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('family_code', models.CharField(max_length=30, unique=True, verbose_name='Code famille')),
                ('name', models.CharField(max_length=255, verbose_name='Nom de famille')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Adresse')),
                ('main_phone', models.CharField(blank=True, max_length=30, verbose_name='Téléphone principal')),
                ('main_email', models.EmailField(blank=True, max_length=254, verbose_name='Email principal')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=20, verbose_name='Statut')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='families', to='hierarchy.entitehierarchique', verbose_name='Église')),
            ],
            options={
                'verbose_name': 'Famille',
                'verbose_name_plural': 'Familles',
                'ordering': ['name'],
            },
        ),
    ]
