# Generated by Django 5.2.17 on 2026-08-18 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hierarchy', '0001_initial'),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visiteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(blank=True, max_length=128, verbose_name='Prénom')),
                ('last_name', models.CharField(blank=True, max_length=128, verbose_name='Nom')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('first_visit_date', models.DateField(verbose_name='Date de première visite')),
                ('reason_for_visit', models.CharField(blank=True, max_length=255, verbose_name='Motif de visite')),
                ('wants_follow_up', models.BooleanField(default=False, verbose_name='Souhaite un suivi')),
                ('consent_contact', models.BooleanField(default=False, verbose_name='Consentement de contact')),
                ('follow_up_status', models.CharField(choices=[('NEW', 'Nouveau'), ('TO_CONTACT', 'À contacter'), ('CONTACTED', 'Contacté'), ('RETURNED', 'Revenu'), ('BECAME_MEMBER', 'Devenu membre'), ('DO_NOT_CONTACT', 'Ne pas contacter'), ('ARCHIVED', 'Archivé')], default='NEW', max_length=20, verbose_name='Statut de suivi')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visitors', to='hierarchy.entitehierarchique', verbose_name='Église visitée')),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invited_visitors', to='members.membre', verbose_name='Invité par')),
            ],
            options={
                'verbose_name': 'Visiteur',
                'verbose_name_plural': 'Visiteurs',
                'ordering': ['-first_visit_date'],
            },
        ),
    ]
