# Generated by Django 5.2.17 on 2026-08-18 13:52

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('donations', '0001_initial'),
        ('hierarchy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FondsAffecte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128, verbose_name='Nom')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Code')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Fonds affecté',
                'verbose_name_plural': 'Fonds affectés',
            },
        ),
        migrations.CreateModel(
            name='RegleReversement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Nom de la règle')),
                ('denomination', models.CharField(choices=[('CATHOLIC', 'Catholique'), ('PROTESTANT', 'Protestante'), ('ADVENTIST', 'Adventiste')], max_length=30)),
                ('source_entity_type', models.CharField(max_length=40, verbose_name="Type d'entité source")),
                ('donation_type', models.CharField(choices=[('TITHE', 'Dîme'), ('GENERAL_OFFERING', 'Offrande générale'), ('SPECIAL_OFFERING', 'Offrande spéciale'), ('DESIGNATED_FUND', 'Fonds désigné'), ('OTHER', 'Autre')], max_length=30)),
                ('version', models.PositiveIntegerField(default=1, verbose_name='Version')),
                ('effective_start_date', models.DateField(verbose_name="Date de début d'effet")),
                ('effective_end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('ACTIVE', 'Active'), ('SUPERSEDED', 'Remplacée'), ('RETIRED', 'Retirée')], default='DRAFT', max_length=20)),
                ('is_complete', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_redistribution_rules', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_redistribution_rules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Règle de reversement',
                'verbose_name_plural': 'Règles de reversement',
                'ordering': ['-effective_start_date', '-version'],
                'unique_together': {('denomination', 'source_entity_type', 'donation_type', 'version')},
            },
        ),
        migrations.CreateModel(
            name='Redistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destination_type', models.CharField(choices=[('HIERARCHICAL_LEVEL', 'Niveau hiérarchique'), ('DESIGNATED_FUND', 'Fonds affecté')], max_length=20)),
                ('received_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('applied_percentage', models.DecimalField(decimal_places=2, max_digits=6)),
                ('retained_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('transferred_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('calculation_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('COMPUTED', 'Calculée'), ('CORRECTED', 'Corrigée'), ('CANCELLED', 'Annulée')], default='COMPUTED', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('designated_fund', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='redistribution.fondsaffecte')),
                ('destination_entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_redistributions', to='hierarchy.entitehierarchique')),
                ('donation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='redistributions', to='donations.don')),
                ('source_entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_redistributions', to='hierarchy.entitehierarchique')),
                ('rule_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='redistributions', to='redistribution.reglereversement')),
            ],
            options={
                'verbose_name': 'Redistribution',
                'verbose_name_plural': 'Redistributions',
                'ordering': ['-calculation_date'],
            },
        ),
        migrations.CreateModel(
            name='LigneReversement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destination_type', models.CharField(choices=[('HIERARCHICAL_LEVEL', 'Niveau hiérarchique'), ('DESIGNATED_FUND', 'Fonds affecté')], max_length=20)),
                ('target_entity_type', models.CharField(blank=True, max_length=40, null=True)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('calculation_order', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('designated_fund', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='redistribution.fondsaffecte')),
                ('target_entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hierarchy.entitehierarchique')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='redistribution.reglereversement')),
            ],
            options={
                'verbose_name': 'Ligne de reversement',
                'ordering': ['calculation_order'],
            },
        ),
    ]
