# Generated by Django 5.2.17 on 2026-08-19 11:17

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hierarchy', '0002_entitehierarchique_city'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Nom de la chapelle')),
                ('code', models.CharField(max_length=50, verbose_name='Code')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Adresse')),
                ('city', models.CharField(blank=True, max_length=128, verbose_name='Ville')),
                ('neighborhood', models.CharField(blank=True, max_length=128, verbose_name='Quartier')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='Pays')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Téléphone')),
                ('gps_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)], verbose_name='Latitude')),
                ('gps_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)], verbose_name='Longitude')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapels', to='hierarchy.entitehierarchique', verbose_name='Église mère')),
                ('leader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_chapels', to=settings.AUTH_USER_MODEL, verbose_name='Responsable de chapelle')),
            ],
            options={
                'verbose_name': 'Chapelle',
                'verbose_name_plural': 'Chapelles',
                'ordering': ['name'],
                'unique_together': {('code', 'church')},
            },
        ),
    ]
