# Generated by Django 5.2.17 on 2026-08-25 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapelle',
            name='capacity',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Capacité'),
        ),
        migrations.AddField(
            model_name='chapelle',
            name='observations',
            field=models.TextField(blank=True, verbose_name='Observations'),
        ),
        migrations.AddField(
            model_name='chapelle',
            name='worship_schedule',
            field=models.CharField(blank=True, max_length=255, verbose_name='Horaires de culte'),
        ),
    ]
