# Generated by Django 5.2.17 on 2026-08-18 13:52

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
        ('hierarchy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('event_type', models.CharField(choices=[('WORSHIP', 'Culte'), ('MEETING', 'Réunion'), ('CONFERENCE', 'Conférence'), ('OUTREACH', 'Évangélisation'), ('YOUTH', 'Jeunesse'), ('CHARITY', 'Charité'), ('TRAINING', 'Formation'), ('CELEBRATION', 'Célébration'), ('OTHER', 'Autre')], max_length=30, verbose_name='Type')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('president_or_leader', models.CharField(blank=True, max_length=255, verbose_name='Président / Responsable')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='Lieu')),
                ('start_datetime', models.DateTimeField(verbose_name='Début')),
                ('end_datetime', models.DateTimeField(verbose_name='Fin')),
                ('expected_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Budget prévu')),
                ('actual_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Budget réel')),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('PLANNED', 'Planifié'), ('PUBLISHED', 'Publié'), ('COMPLETED', 'Terminé'), ('CANCELLED', 'Annulé')], default='DRAFT', max_length=20, verbose_name='Statut')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='events/attachments/')),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='hierarchy.entitehierarchique', verbose_name='Église')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='departments.departement', verbose_name='Département')),
                ('organizer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organized_events', to=settings.AUTH_USER_MODEL, verbose_name='Organisateur')),
            ],
            options={
                'verbose_name': 'Événement',
                'verbose_name_plural': 'Événements',
                'ordering': ['-start_datetime'],
            },
        ),
        migrations.CreateModel(
            name='ParticipantEvenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('INVITED', 'Invité'), ('REGISTERED', 'Inscrit'), ('PRESENT', 'Présent'), ('ABSENT', 'Absent'), ('EXCUSED', 'Excusé')], default='INVITED', max_length=20, verbose_name='Statut')),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('attendance_time', models.DateTimeField(blank=True, null=True, verbose_name='Heure de présence')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='events.evenement', verbose_name='Événement')),
            ],
            options={
                'verbose_name': 'Participant',
                'verbose_name_plural': 'Participants',
            },
        ),
    ]
