# Generated by Django 5.2.17 on 2026-08-18 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('members', '0001_initial'),
        ('visitors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participantevenement',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_participations', to='members.membre', verbose_name='Membre'),
        ),
        migrations.AddField(
            model_name='participantevenement',
            name='visitor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_participations', to='visitors.visiteur', verbose_name='Visiteur'),
        ),
        migrations.AlterUniqueTogether(
            name='participantevenement',
            unique_together={('event', 'member'), ('event', 'visitor')},
        ),
    ]
