# Generated by Django 5.2.17 on 2026-08-18 13:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('CREATE', 'Création'), ('UPDATE', 'Modification'), ('DELETE', 'Suppression'), ('ARCHIVE', 'Archivage'), ('LOGIN', 'Connexion'), ('LOGIN_FAILED', 'Échec de connexion'), ('LOGOUT', 'Déconnexion'), ('PASSWORD_CHANGE', 'Changement de mot de passe'), ('TRANSFER', 'Transfert'), ('VALIDATE', 'Validation'), ('REJECT', 'Rejet'), ('CANCEL', 'Annulation'), ('CORRECT', 'Correction'), ('EXPORT', 'Export'), ('DOWNLOAD', 'Téléchargement'), ('VIEW', 'Consultation'), ('ROLE_CHANGE', 'Changement de rôle'), ('RECEIPT_GENERATED', 'Reçu généré')], max_length=40, verbose_name='Action')),
                ('app_label', models.CharField(max_length=100, verbose_name='Application')),
                ('model_name', models.CharField(max_length=100, verbose_name='Modèle')),
                ('object_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='Objet ID')),
                ('object_repr', models.CharField(blank=True, max_length=255, null=True, verbose_name='Représentation')),
                ('old_values', models.JSONField(blank=True, null=True, verbose_name='Anciennes valeurs')),
                ('new_values', models.JSONField(blank=True, null=True, verbose_name='Nouvelles valeurs')),
                ('reason', models.CharField(blank=True, max_length=500, null=True, verbose_name='Motif')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('user_agent', models.CharField(blank=True, max_length=500, null=True, verbose_name='Navigateur')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': "Journal d'audit",
                'verbose_name_plural': "Journal d'audit",
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['app_label', 'model_name', 'object_id'], name='audit_journ_app_lab_9d7aa5_idx'), models.Index(fields=['action'], name='audit_journ_action_fba5af_idx'), models.Index(fields=['user'], name='audit_journ_user_id_d52e87_idx')],
            },
        ),
    ]
