# Generated by Django 5.2.17 on 2026-08-18 13:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hierarchy', '0001_initial'),
        ('members', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SuiviPastoral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.CharField(max_length=255, verbose_name='Motif')),
                ('action_type', models.CharField(choices=[('VISIT', 'Visite'), ('PHONE_CALL', 'Appel téléphonique'), ('COUNSELING', 'Conseil'), ('PRAYER', 'Prière'), ('FAMILY_SUPPORT', 'Soutien familial'), ('SOCIAL_ASSISTANCE', 'Assistance sociale'), ('SPIRITUAL_SUPPORT', 'Soutien spirituel'), ('OTHER', 'Autre')], max_length=30, verbose_name="Type d'action")),
                ('action_date', models.DateField(verbose_name="Date de l'action")),
                ('next_action_date', models.DateField(blank=True, null=True, verbose_name='Prochaine action')),
                ('status', models.CharField(choices=[('OPEN', 'Ouvert'), ('IN_PROGRESS', 'En cours'), ('PENDING', 'En attente'), ('CLOSED', 'Clôturé'), ('ARCHIVED', 'Archivé')], default='OPEN', max_length=20, verbose_name='Statut')),
                ('confidentiality_level', models.CharField(choices=[('STANDARD', 'Standard'), ('RESTRICTED', 'Restreint'), ('HIGHLY_CONFIDENTIAL', 'Hautement confidentiel')], default='STANDARD', max_length=30, verbose_name='Niveau de confidentialité')),
                ('details', models.TextField(blank=True, verbose_name='Détails')),
                ('notes', models.TextField(blank=True, verbose_name='Notes internes')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Clôturé le')),
                ('assigned_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_followups', to=settings.AUTH_USER_MODEL, verbose_name='Responsable assigné')),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pastoral_followups', to='hierarchy.entitehierarchique', verbose_name='Église')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_followups', to=settings.AUTH_USER_MODEL, verbose_name='Clôturé par')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_followups', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pastoral_followups', to='members.membre', verbose_name='Membre')),
            ],
            options={
                'verbose_name': 'Suivi pastoral',
                'verbose_name_plural': 'Suivis pastoraux',
                'ordering': ['-action_date'],
            },
        ),
    ]
