# Generated by Django 5.2.17 on 2026-08-18 13:52

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
        ('hierarchy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fiscal_year', models.PositiveIntegerField(verbose_name='Exercice fiscal')),
                ('name', models.CharField(max_length=255, verbose_name='Nom')),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('SUBMITTED', 'Soumis'), ('APPROVED', 'Approuvé'), ('CLOSED', 'Clôturé')], default='DRAFT', max_length=20, verbose_name='Statut')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_budgets', to=settings.AUTH_USER_MODEL)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budgets', to='hierarchy.entitehierarchique', verbose_name='Église')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_budgets', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budgets', to='departments.departement', verbose_name='Département')),
            ],
            options={
                'verbose_name': 'Budget',
                'verbose_name_plural': 'Budgets',
                'unique_together': {('church', 'department', 'fiscal_year')},
            },
        ),
        migrations.CreateModel(
            name='CategorieFinanciere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128, verbose_name='Nom')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Code')),
                ('category_type', models.CharField(choices=[('INCOME', 'Recette'), ('EXPENSE', 'Dépense')], max_length=10, verbose_name='Type')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('church', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_categories', to='hierarchy.entitehierarchique', verbose_name='Église (null = global)')),
            ],
            options={
                'verbose_name': 'Catégorie financière',
                'verbose_name_plural': 'Catégories financières',
                'ordering': ['category_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Depense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Montant')),
                ('date', models.DateField(verbose_name='Date')),
                ('beneficiary', models.CharField(blank=True, max_length=255, verbose_name='Bénéficiaire')),
                ('payment_method', models.CharField(choices=[('CASH', 'Espèces'), ('BANK_TRANSFER', 'Virement bancaire'), ('MOBILE_MONEY', 'Mobile money'), ('CHECK', 'Chèque'), ('CARD', 'Carte'), ('OTHER', 'Autre')], default='CASH', max_length=20, verbose_name='Mode de paiement')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='Référence')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('SUBMITTED', 'Soumis'), ('APPROVED', 'Approuvé'), ('REJECTED', 'Rejeté'), ('CANCELLED', 'Annulé')], default='DRAFT', max_length=20, verbose_name='Statut')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='finance/depenses/')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_depenses', to=settings.AUTH_USER_MODEL, verbose_name='Approuvé par')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='depenses', to='finance.categoriefinanciere', verbose_name='Catégorie')),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='depenses', to='hierarchy.entitehierarchique', verbose_name='Église')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_depenses', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depenses', to='departments.departement', verbose_name='Département')),
            ],
            options={
                'verbose_name': 'Dépense',
                'verbose_name_plural': 'Dépenses',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Recette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Montant')),
                ('date', models.DateField(verbose_name='Date')),
                ('source', models.CharField(blank=True, max_length=255, verbose_name='Source')),
                ('payment_method', models.CharField(choices=[('CASH', 'Espèces'), ('BANK_TRANSFER', 'Virement bancaire'), ('MOBILE_MONEY', 'Mobile money'), ('CHECK', 'Chèque'), ('CARD', 'Carte'), ('OTHER', 'Autre')], default='CASH', max_length=20, verbose_name='Mode de paiement')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='Référence')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('SUBMITTED', 'Soumis'), ('APPROVED', 'Approuvé'), ('REJECTED', 'Rejeté'), ('CANCELLED', 'Annulé')], default='DRAFT', max_length=20, verbose_name='Statut')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='finance/recettes/')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_recettes', to=settings.AUTH_USER_MODEL, verbose_name='Approuvé par')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recettes', to='finance.categoriefinanciere', verbose_name='Catégorie')),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recettes', to='hierarchy.entitehierarchique', verbose_name='Église')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_recettes', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recettes', to='departments.departement', verbose_name='Département')),
            ],
            options={
                'verbose_name': 'Recette',
                'verbose_name_plural': 'Recettes',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Justificatif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='finance/justificatifs/', verbose_name='Fichier')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Description')),
                ('depense', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='justificatifs', to='finance.depense', verbose_name='Dépense')),
                ('recette', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='justificatifs', to='finance.recette', verbose_name='Recette')),
            ],
            options={
                'verbose_name': 'Justificatif',
            },
        ),
        migrations.CreateModel(
            name='ValidationFinanciere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('decision', models.CharField(choices=[('APPROVED', 'Approuvé'), ('REJECTED', 'Rejeté')], max_length=20, verbose_name='Décision')),
                ('reason', models.CharField(blank=True, max_length=500, verbose_name='Motif')),
                ('validated_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('depense', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='validations', to='finance.depense')),
                ('recette', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='validations', to='finance.recette')),
                ('validated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='financial_validations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Validation financière',
            },
        ),
        migrations.CreateModel(
            name='LigneBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('planned_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant prévu')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='finance.budget', verbose_name='Budget')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budget_lines', to='finance.categoriefinanciere', verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Ligne budgétaire',
                'verbose_name_plural': 'Lignes budgétaires',
                'unique_together': {('budget', 'category')},
            },
        ),
    ]
