# Generated by Django 5.2.17 on 2026-08-18 13:52

import apps.accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('first_name', models.CharField(max_length=128, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=128, verbose_name='Nom')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Téléphone')),
                ('role', models.CharField(choices=[('SUPER_ADMIN', 'Super administrateur'), ('DIVISION_ADMIN', 'Administrateur de Division'), ('UNION_ADMIN', "Administrateur d'Union"), ('FEDERATION_ADMIN', 'Administrateur de Fédération'), ('LOCAL_LEADER', 'Leader local'), ('TREASURER', 'Trésorier'), ('DEPARTMENT_LEADER', 'Responsable de département'), ('PASTORAL_LEADER', 'Responsable pastoral'), ('AUDITOR', 'Auditeur'), ('MEMBER', 'Membre')], default='MEMBER', max_length=30, verbose_name='Rôle')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Staff')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
                'ordering': ['last_name', 'first_name'],
            },
            managers=[
                ('objects', apps.accounts.models.UserManager()),
            ],
        ),
    ]
