# Generated by Django 5.2.17 on 2026-08-25 02:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('hierarchy', '0002_entitehierarchique_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRoleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role_code', models.CharField(choices=[('SUPER_ADMIN', 'Super administrateur'), ('DIVISION_ADMIN', 'Administrateur de Division'), ('UNION_ADMIN', "Administrateur d'Union"), ('FEDERATION_ADMIN', 'Administrateur de Fédération'), ('LOCAL_LEADER', 'Leader local'), ('TREASURER', 'Trésorier'), ('DEPARTMENT_LEADER', 'Responsable de département'), ('PASTORAL_LEADER', 'Responsable pastoral'), ('AUDITOR', 'Auditeur'), ('MEMBER', 'Membre')], max_length=30, verbose_name='Role')),
                ('can_manage_descendants', models.BooleanField(default=False, verbose_name='Peut gerer les descendants')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('starts_at', models.DateField(blank=True, null=True, verbose_name='Date de debut')),
                ('ends_at', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_roles', to=settings.AUTH_USER_MODEL, verbose_name='Attribue par')),
                ('scope_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to='hierarchy.entitehierarchique', verbose_name='Entite de portee')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Attribution de role',
                'verbose_name_plural': 'Attributions de roles',
                'unique_together': {('user', 'role_code', 'scope_entity')},
            },
        ),
    ]
