# Generated by Django 5.2.17 on 2026-08-18 13:52

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('families', '0001_initial'),
        ('hierarchy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Membre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Supprimé le')),
                ('member_number', models.CharField(max_length=30, unique=True, verbose_name='Numéro de membre')),
                ('first_name', models.CharField(max_length=128, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=128, verbose_name='Nom')),
                ('gender', models.CharField(choices=[('MALE', 'Masculin'), ('FEMALE', 'Féminin'), ('OTHER', 'Autre')], max_length=10, verbose_name='Genre')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Date de naissance')),
                ('phone', models.CharField(blank=True, max_length=30, validators=[django.core.validators.RegexValidator(regex='^\\+?[\\d\\s\\-]{8,20}$')], verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Adresse')),
                ('neighborhood', models.CharField(blank=True, max_length=128, verbose_name='Quartier')),
                ('marital_status', models.CharField(choices=[('SINGLE', 'Célibataire'), ('MARRIED', 'Marié(e)'), ('DIVORCED', 'Divorcé(e)'), ('WIDOWED', 'Veuf/Veuve'), ('OTHER', 'Autre')], default='SINGLE', max_length=20, verbose_name='État civil')),
                ('occupation', models.CharField(blank=True, max_length=128, verbose_name='Profession')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='members/photos/', verbose_name='Photo')),
                ('emergency_contact_name', models.CharField(blank=True, max_length=128, verbose_name="Contact d'urgence (nom)")),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=30, verbose_name="Contact d'urgence (téléphone)")),
                ('membership_date', models.DateField(verbose_name="Date d'adhésion")),
                ('status', models.CharField(choices=[('PROSPECT', 'Prospect'), ('ACTIVE', 'Actif'), ('INACTIVE', 'Inactif'), ('TRANSFERRED', 'Transféré'), ('SUSPENDED', 'Suspendu'), ('DECEASED', 'Décédé'), ('ARCHIVED', 'Archivé')], default='ACTIVE', max_length=20, verbose_name='Statut')),
                ('baptism_place', models.CharField(blank=True, max_length=255, verbose_name='Lieu de baptême')),
                ('baptism_date', models.DateField(blank=True, null=True, verbose_name='Date de baptême')),
                ('baptized_by', models.CharField(blank=True, max_length=255, verbose_name='Baptisé par')),
                ('consent_email', models.BooleanField(default=False, verbose_name='Consentement email')),
                ('consent_whatsapp', models.BooleanField(default=False, verbose_name='Consentement WhatsApp')),
                ('consent_data_processing', models.BooleanField(default=False, verbose_name='Consentement traitement des données')),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='members', to='hierarchy.entitehierarchique', verbose_name='Église')),
                ('family', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='families.famille', verbose_name='Famille')),
            ],
            options={
                'verbose_name': 'Membre',
                'verbose_name_plural': 'Membres',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='HistoriqueAffectationMembre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transfer_date', models.DateField(verbose_name='Date du transfert')),
                ('transfer_reason', models.CharField(blank=True, max_length=500, verbose_name='Motif du transfert')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('APPROVED', 'Approuvé'), ('REJECTED', 'Rejeté'), ('CANCELLED', 'Annulé')], default='PENDING', max_length=20, verbose_name='Statut')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_approvals', to=settings.AUTH_USER_MODEL, verbose_name='Approuvé par')),
                ('new_church', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_to', to='hierarchy.entitehierarchique', verbose_name='Église de destination')),
                ('previous_church', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_from', to='hierarchy.entitehierarchique', verbose_name="Église d'origine")),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_requests', to=settings.AUTH_USER_MODEL, verbose_name='Demandé par')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfer_history', to='members.membre', verbose_name='Membre')),
            ],
            options={
                'verbose_name': "Historique d'affectation",
                'verbose_name_plural': "Historiques d'affectation",
                'ordering': ['-transfer_date'],
            },
        ),
        migrations.AddIndex(
            model_name='membre',
            index=models.Index(fields=['church', 'status'], name='members_mem_church__636e80_idx'),
        ),
        migrations.AddIndex(
            model_name='membre',
            index=models.Index(fields=['last_name', 'first_name'], name='members_mem_last_na_8f98cc_idx'),
        ),
    ]
