# Generated by Django 5.2.17 on 2026-08-19 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churches', '__first__'),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membre',
            name='chapel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='churches.chapelle', verbose_name='Chapelle'),
        ),
    ]
