# Generated by Django 5.2.17 on 2026-08-18 13:52

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hierarchy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembreDepartement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.PositiveIntegerField(verbose_name='Année')),
                ('role_in_department', models.CharField(blank=True, max_length=100, verbose_name='Rôle')),
                ('start_date', models.DateField(verbose_name='Date de début')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Membre du département',
                'verbose_name_plural': 'Membres du département',
            },
        ),
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Nom')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Code')),
                ('department_type', models.CharField(choices=[('ADMINISTRATION', 'Administration'), ('WORSHIP', 'Culte et adoration'), ('MUSIC', 'Musique'), ('YOUTH', 'Jeunesse'), ('SABBATH_SCHOOL', 'École du Sabbat'), ('CHILDREN', 'Enfants'), ('WOMEN', 'Femmes'), ('MEN', 'Hommes'), ('SOCIAL', 'Action sociale'), ('COMMUNICATION', 'Communication'), ('OTHER', 'Autre')], default='OTHER', max_length=30, verbose_name='Type')),
                ('annual_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Budget annuel')),
                ('start_date', models.DateField(verbose_name='Date de début')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='departments', to='hierarchy.entitehierarchique', verbose_name='Église')),
            ],
            options={
                'verbose_name': 'Département',
                'verbose_name_plural': 'Départements',
                'ordering': ['name'],
            },
        ),
    ]
