# Generated by Django 5.2.17 on 2026-08-18 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='departement',
            name='deputy_leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deputy_departments', to='members.membre', verbose_name='Adjoint'),
        ),
        migrations.AddField(
            model_name='departement',
            name='leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_departments', to='members.membre', verbose_name='Responsable'),
        ),
        migrations.AddField(
            model_name='membredepartement',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='departments.departement', verbose_name='Département'),
        ),
        migrations.AddField(
            model_name='membredepartement',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='department_memberships', to='members.membre', verbose_name='Membre'),
        ),
        migrations.AlterUniqueTogether(
            name='membredepartement',
            unique_together={('member', 'department', 'year')},
        ),
    ]
