# Generated by Django 5.2.17 on 2026-08-25 00:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_initial'),
        ('members', '0002_membre_chapel'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanAnnuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.PositiveIntegerField(verbose_name='Annee')),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('planned_date', models.DateField(blank=True, null=True, verbose_name='Date prevue')),
                ('status', models.CharField(choices=[('PLANNED', 'Planifie'), ('IN_PROGRESS', 'En cours'), ('DONE', 'Termine'), ('CANCELLED', 'Annule')], default='PLANNED', max_length=20, verbose_name='Statut')),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Budget prevu')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annual_plans', to='departments.departement', verbose_name='Departement')),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planned_activities', to='members.membre', verbose_name='Responsable')),
            ],
            options={
                'verbose_name': 'Plan annuel',
                'verbose_name_plural': 'Plans annuels',
                'ordering': ['planned_date'],
            },
        ),
    ]
