# Generated by Django 5.2.17 on 2026-08-18 13:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EntiteHierarchique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Supprimé le')),
                ('name', models.CharField(max_length=255, verbose_name='Nom')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Code')),
                ('entity_type', models.CharField(choices=[('GENERAL_CONFERENCE', 'Conférence Générale'), ('DIVISION', 'Division'), ('UNION', 'Union'), ('FEDERATION', 'Fédération'), ('MISSION', 'Mission'), ('LOCAL_CHURCH', 'Église locale'), ('DIOCESE', 'Diocèse'), ('PARISH', 'Paroisse'), ('PROTESTANT_UNION', 'Union Protestante'), ('PROTESTANT_CHURCH', 'Église Protestante')], max_length=40, verbose_name='Type')),
                ('denomination', models.CharField(choices=[('CATHOLIC', 'Catholique'), ('PROTESTANT', 'Protestante'), ('ADVENTIST', 'Adventiste')], max_length=30, verbose_name='Dénomination')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='Pays')),
                ('continent', models.CharField(blank=True, max_length=50, verbose_name='Continent')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Adresse')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('gps_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude')),
                ('gps_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='hierarchy.entitehierarchique', verbose_name='Entité parente')),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_entities', to=settings.AUTH_USER_MODEL, verbose_name='Responsable')),
            ],
            options={
                'verbose_name': 'Entité hiérarchique',
                'verbose_name_plural': 'Entités hiérarchiques',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['entity_type'], name='hierarchy_e_entity__490de7_idx'), models.Index(fields=['denomination'], name='hierarchy_e_denomin_0c874d_idx'), models.Index(fields=['parent'], name='hierarchy_e_parent__86190d_idx')],
            },
        ),
    ]
