# Generated by Django 5.2.17 on 2026-08-19 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hierarchy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entitehierarchique',
            name='city',
            field=models.CharField(blank=True, max_length=128, verbose_name='Ville'),
        ),
    ]
