# Generated by Django 5.2.17 on 2026-08-18 13:52

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hierarchy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('receipt_number', models.CharField(max_length=30, unique=True, verbose_name='Numéro de reçu')),
                ('issued_at', models.DateTimeField(auto_now_add=True, verbose_name='Émis le')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='receipts/')),
                ('sent_by_email', models.BooleanField(default=False, verbose_name='Envoyé par email')),
                ('sent_by_whatsapp', models.BooleanField(default=False, verbose_name='Envoyé par WhatsApp')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Envoyé le')),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('ISSUED', 'Émis'), ('SENT', 'Envoyé'), ('CANCELLED', 'Annulé')], default='ISSUED', max_length=20, verbose_name='Statut')),
            ],
            options={
                'verbose_name': 'Reçu',
                'verbose_name_plural': 'Reçus',
            },
        ),
        migrations.CreateModel(
            name='Don',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('donation_number', models.CharField(max_length=30, unique=True, verbose_name='Numéro de don')),
                ('donation_type', models.CharField(choices=[('TITHE', 'Dîme'), ('GENERAL_OFFERING', 'Offrande générale'), ('SPECIAL_OFFERING', 'Offrande spéciale'), ('DESIGNATED_FUND', 'Fonds désigné'), ('OTHER', 'Autre')], max_length=30, verbose_name='Type de don')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Montant')),
                ('donation_date', models.DateField(verbose_name='Date du don')),
                ('received_at', models.DateTimeField(auto_now_add=True, verbose_name='Enregistré le')),
                ('payment_method', models.CharField(choices=[('CASH', 'Espèces'), ('BANK_TRANSFER', 'Virement bancaire'), ('MOBILE_MONEY', 'Mobile money'), ('CHECK', 'Chèque'), ('CARD', 'Carte'), ('OTHER', 'Autre')], default='CASH', max_length=20, verbose_name='Mode de paiement')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='Référence')),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('PENDING_VALIDATION', 'En attente de validation'), ('VALIDATED', 'Validé'), ('REJECTED', 'Rejeté'), ('CANCELLATION_REQUESTED', 'Annulation demandée'), ('CANCELLED', 'Annulé'), ('CORRECTED', 'Corrigé')], default='PENDING_VALIDATION', max_length=30, verbose_name='Statut')),
                ('validated_at', models.DateTimeField(blank=True, null=True, verbose_name='Validé le')),
                ('cancellation_reason', models.CharField(blank=True, max_length=500, verbose_name="Motif d'annulation")),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_donations', to=settings.AUTH_USER_MODEL)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='donations', to='hierarchy.entitehierarchique', verbose_name='Église')),
            ],
            options={
                'verbose_name': 'Don',
                'verbose_name_plural': 'Dons',
                'ordering': ['-donation_date'],
            },
        ),
    ]
