# Generated by Django 5.2.17 on 2026-09-09 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='don',
            name='member_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email du membre (pour reçu)'),
        ),
        migrations.AddField(
            model_name='don',
            name='member_phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='Téléphone du membre (pour WhatsApp)'),
        ),
    ]
